services:
  - type: web
    name: ghostchat-backend
    env: java

    rootDir: ghostchat

    buildCommand: ./mvnw clean package -DskipTests

    startCommand: java -jar target/ghostchat-0.0.1-SNAPSHOT.jar

    plan: free

    envVars:
      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: REDIS_HOST
        sync: false

      - key: REDIS_PORT
        sync: false

      - key: REDIS_PASSWORD
        sync: false

      - key: FRONTEND_URL
        sync: false