spring.application.name=ghostchat

spring.datasource.url=jdbc:mysql://localhost:3306/ghostchat
spring.datasource.username=root
spring.datasource.password=101208914

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=mySuperSecretKeyForGhostChatApplication123456
jwt.expiration=86400000
